config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :organisations
  devise_for :users
  devise_scope :user do
    get 'users/sign_out', to: 'users/sessions#destroy'
  end

  resources :users
  namespace :api do
    namespace :v1 do
      resources :users, only: [:show] do
        resources :tags_users, only: [:index, :create, :destroy]
      end
    end
  end

  get 'about', to: 'home#about'
  get 'cookies', to: 'home#cookies'
  get 'contact', to: 'home#contact'
  root to: 'home#index'

  match '*path', to: 'home#index', via: :all
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/biography.rb
class Biography < ApplicationRecord
  belongs_to :user
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  mount_uploader :avatar, ::OrganisationAvatarUploader
  has_many :organisations_tags
  has_many :organisations_users
  has_many :projects

  has_many :tags, through: :organisations_tags
  has_many :users, through: :organisations_users
end

app/models/organisation_contact.rb
class OrganisationContact < ApplicationRecord
  belongs_to :organisation
end

app/models/organisations_tag.rb
class OrganisationsTag < ApplicationRecord
  belongs_to :organisation
  belongs_to :tag
end

app/models/organisations_user.rb
class OrganisationsUser < ApplicationRecord
  belongs_to :user
  belongs_to :organisation

  enum relation_type: [:organisation_worker, :volunteer]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :organisation

  has_many :projects_tags
  has_many :projects_users

  has_many :users, through: :projects_users
  has_many :tags, through: :projects_tags

  enum status: [:draft, :not_started, :in_progress, :finished]
end

app/models/projects_tag.rb
class ProjectsTag < ApplicationRecord
  belongs_to :project
  belongs_to :tag
end

app/models/projects_user.rb
class ProjectsUser < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, through: :roles_users

  enum role_type: [:admin, :organisation_admin, :volunteer]
end

app/models/roles_user.rb
class RolesUser < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tags_users
  has_many :projects_tags
  has_many :organisations_tags

  has_many :organisations, through: :organisations_tags
  has_many :users, through: :tags_users
  has_many :projects, through: :projects_tags

  enum tag_type: [:skill, :focus]
end

app/models/tags_user.rb
class TagsUser < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :avatar, ::UserAvatarUploader

  devise :database_authenticatable, :registerable, :lockable, :trackable, :recoverable, :rememberable, :validatable

  has_many :tags_users
  has_many :roles_users
  has_many :projects_users
  has_many :organisations_users

  has_many :organisations, through: :organisations_users
  has_many :projects, through: :projects_users
  has_many :tags, through: :tags_users
  has_many :roles, through: :roles_users
  has_one :biography
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def serialized_resource(resource)
    return {} if resource.nil?

    resource
  end


  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def cookies
  end

  def contact
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController

  def index
    @organisations = Organisation.all

    render :index
  end

  def show
    @organisation = Organisation.find(params[:id])
  end

  private

    def organisation_params
      params.require(:organisation).permit()
    end

end

app/controllers/react_examples_controller.rb
class ReactExamplesController < ApplicationController
  def component
    @name = 'test'
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def respond_to_on_destroy
    # We actually need to hardcode this as Rails default responder doesn't
    # support returning empty response on GET request
    respond_to do |format|
      format.all { redirect_to root_path }
      format.any(*navigational_formats) { redirect_to after_sign_out_path_for(resource_name) }
    end
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_permission, only: [:edit, :update]

  def show
  end

  def edit
    render :edit, user: @current_user
  end

  def update
    current_user.update(user_params)

    redirect_to edit_user_path
  end

  private

  def check_permission
    redirect_to(root_path) unless current_user.id == params[:id]
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/organisations/_form.html.erb
<%= form_with(model: organisation, local: true) do |form| %>
  <% if organisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>

      <ul>
      <% organisation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organisations/edit.html.erb
<h1>Editing Organisation</h1>

<%= render 'form', organisation: @organisation %>

<%= link_to 'Show', @organisation %> |
<%= link_to 'Back', organisations_path %>

app/views/organisations/index.html.erb
<p id="notice"><%= notice %></p>

<div class="dig-organisations-content">
  <div class="dig-list-header">
  </div>

  <div class="dig-resource-list">
    <% @organisations.each do |organisation| %>
      <div class="dig-resource-item">
        <div class="dig-resource-item-content">
          <div class="dig-resource-item-picture">
            <% if organisation.avatar? %>
              <%= image_tag(organisation.avatar_url) %>
            <% else %>
              <%= image_tag('blank_profile_organisation.svg') %>
            <% end %>
          </div>
          <div class="resource-item-name">
            <h2><%= organisation.name %></h2>
          </div>
          <div class="dig-resource-item-description">
            <%= organisation.description %>
          </div>
        </div>
        <div class="dig-resource-item-footer">
          <%= button_to("Wywietl profil", organisation_path(organisation)) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/organisations/new.html.erb
<h1>New Organisation</h1>

<%= render 'form', organisation: @organisation %>

<%= link_to 'Back', organisations_path %>

app/views/organisations/show.html.erb
<div class="background-image blurred"><%= image_tag("main_1.png")%></div>
<div class="dig-organisation">
  <div class="dig-org-content">
    <div class="dig-org-row">
      <div class="dig-org-picture">
        <% if @organisation.avatar? %>
          <%= image_tag(@organisation.avatar_url) %>
        <% else %>
          <%= image_tag('blank_profile_organisation.svg') %>
        <% end %>
      </div>
      <div class="dig-org-name">
        <h2><%= @organisation.name %></h2>
      </div>
      <div class="dig-org-button">
        <%= button_to("Dołącz", organisation_path(@organisation)) %>
      </div>
    </div>

    <div class="dig-org-row">
      <h3>Technologie:</h3>
      <div class="dig-org-tags">
        <% @organisation.tags.each do |tag| %>
          <div class="dig-org-tag"><%= tag.name %></div>
        <% end %>
      </div>
    </div>

    <div class="dig-org-row">
      <h3>O firmie</h3>
      <div class="dig-org-description">
        <%= @organisation.description %>
      </div>
    </div>

    <div class="dig-org-row">
      <h3>Dodane projekty</h3>
      <div class="dig-org-projects">
        <%= @organisation.projects.pluck(:name) %>
      </div>
    </div>
  </div>
</div>