config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :organisations
  devise_for :users
  devise_scope :user do
    get 'users/sign_out', to: 'users/sessions#destroy'
  end

  resources :users
  namespace :api do
    namespace :v1 do
      resources :users, only: [:show] do
        resources :tags_users, only: [:index, :create, :destroy]
      end
    end
  end

  get 'about', to: 'home#about'
  get 'cookies', to: 'home#cookies'
  get 'contact', to: 'home#contact'
  root to: 'home#index'

  match '*path', to: 'home#index', via: :all
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/biography.rb
class Biography < ApplicationRecord
  belongs_to :user
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  mount_uploader :avatar, ::OrganisationAvatarUploader
  has_many :organisations_tags
  has_many :organisations_users
  has_many :projects

  has_many :tags, through: :organisations_tags
  has_many :users, through: :organisations_users
end

app/models/organisation_contact.rb
class OrganisationContact < ApplicationRecord
  belongs_to :organisation
end

app/models/organisations_tag.rb
class OrganisationsTag < ApplicationRecord
  belongs_to :organisation
  belongs_to :tag
end

app/models/organisations_user.rb
class OrganisationsUser < ApplicationRecord
  belongs_to :user
  belongs_to :organisation

  enum relation_type: [:organisation_worker, :volunteer]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :organisation

  has_many :projects_tags
  has_many :projects_users

  has_many :users, through: :projects_users
  has_many :tags, through: :projects_tags

  enum status: [:draft, :not_started, :in_progress, :finished]
end

app/models/projects_tag.rb
class ProjectsTag < ApplicationRecord
  belongs_to :project
  belongs_to :tag
end

app/models/projects_user.rb
class ProjectsUser < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, through: :roles_users

  enum role_type: [:admin, :organisation_admin, :volunteer]
end

app/models/roles_user.rb
class RolesUser < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tags_users
  has_many :projects_tags
  has_many :organisations_tags

  has_many :organisations, through: :organisations_tags
  has_many :users, through: :tags_users
  has_many :projects, through: :projects_tags

  enum tag_type: [:skill, :focus]
end

app/models/tags_user.rb
class TagsUser < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :avatar, ::UserAvatarUploader

  devise :database_authenticatable, :registerable, :lockable, :trackable, :recoverable, :rememberable, :validatable

  has_many :tags_users
  has_many :roles_users
  has_many :projects_users
  has_many :organisations_users

  has_many :organisations, through: :organisations_users
  has_many :projects, through: :projects_users
  has_many :tags, through: :tags_users
  has_many :roles, through: :roles_users
  has_one :biography
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def serialized_resource(resource)
    return {} if resource.nil?

    resource
  end


  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def cookies
  end

  def contact
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController

  def index
    @organisations = Organisation.all

    render :index
  end

  def show
    @organisation = Organisation.find(params[:id])
  end

  private

    def organisation_params
      params.require(:organisation).permit()
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_permission, only: [:edit, :update]

  def show
  end

  def edit
    render :edit, user: @current_user
  end

  def update
    current_user.update(user_params)

    redirect_to edit_user_path
  end

  private

  def check_permission
    redirect_to(root_path) unless current_user.id == params[:id]
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_react_hot_assets.html.erb
<% if Rails.env.development? %>
  <script src='http://localhost:8080/assets/react_bundle.js'></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoItGood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="do-it-good-body">
    <%= render "shared/navbar" %>
    <div class="dig-main">
      <%= render "shared/sidebar" if @render_sidebar %>
      <%= yield %>
    </div>

    <%= render 'cookies_eu/consent_banner', link: cookies_path %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="dig-footer">
FOOTER
</footer>

app/views/shared/_navbar.html.erb
<nav class="dig-navbar">
  <div class="dig-navbar__logo">
    <%= link_to(image_tag("logo.svg"), root_path) %>
  </div>
  <div class="dig-navbar__buttons-area">
    <div class="dig-navbar__buttons-area__buttons">
      <%= link_to("Idea", about_path) %>
      <%= link_to("Projekty", organisations_path) %>
      <%= link_to("Organizacje", organisations_path) %>
      <%= link_to("Kontakt", contact_path) %>
      <% if current_user.nil? %>
      <%= link_to("Zaloguj się", new_user_session_path) %>
      <%= link_to("Dołącz do nas", new_user_registration_path, class: "register") %>
      <% else %>
        <div class="dig-dropdown">
          <a href="#" class="dropdown-button">Witaj, <%= current_user.first_name %></a>
          <div class="dropdown-content">
            <ul>
              <li><%= link_to("Moje konto", user_path(current_user)) %></li>
              <li><%= link_to("Moje projekty", user_path(current_user)) %></li>
              <li><%= link_to("Edytuj profil", edit_user_path(current_user)) %></li>
              <li><%= link_to("Wyloguj się", destroy_user_session_path(current_user)) %></li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<aside>
ASIDE
</aside>